# Generated by Django 4.2.4 on 2023-08-08 22:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("filme", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="filmes_vistos",
            field=models.ManyToManyField(to="filme.filme"),
        ),
    ]
